#!/usr/bin/python3

from sys import argv


def factorize_prime():
    try:
        with open(argv[1]) as file:
            for ln in file:
                ln = int(ln)

                if ln % 2 == 0:
                    print("{}={}*{}".format(ln, ln // 2, 2))
                    continue
                x = 3

                while x < ln // 2:
                    if ln % x == 0:
                        print("{}={}*{}".format(ln,
                              ln // x, x))
                        break
                    x += 2

                if x == (ln // 2) + 1:
                    print("{}={}*{}".format(ln, ln, 1))
    except IndexError:
        pass


if __name__ == "__main__":

    factorize_prime()
